apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: rsl5m0aj3-nodejs 
  janus-idp.io/tekton: rsl5m0aj3-nodejs
  backstage.io/kubernetes-id: rsl5m0aj3-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: rsl5m0aj3-nodejs
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  